services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.${NODE_ENV:-development}
    container_name: catch_coin_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    container_name: catch_coin_postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: swagger-ui
    restart: always
    ports:
      - "80:8080"
    environment:
      - SWAGGER_JSON_URL=https://petstore3.swagger.io/api/v3/openapi.json
      # - SWAGGER_JSON=/swagger/swagger.json
    # volumes:
      # - ./swagger:/swagger

volumes:
  postgres_data:
