name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create Release Pull Request
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: monorepo
          config-file: .release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
